preset: laravel

linting: true

enabled:
  - strict
  - unalign_double_arrow

disabled:
  - short_array_syntax

machine:
  php:
    version: 5.4.37


finder:
  exclude:
    - "tests"
  name:
    - "*.php"
